### ISSUE TITLE
Flex week 2 roadmap

### ISSUE THREAD

**Issue by nerik** [developmentseed/co2ordinate#1]
# Proposed architecture

The idea is to package the UI as a dependency (think react-date picker for instance) that could then be called from:
- DS Connect
```
+------------------------------------------+
|     Smartsheet/team.geojson integration   |
|  +-------------------------------------+ |
|  |                 Planner             | |
+  +-------------------------------------+ |
+------------------------------------------+

```

- The public-facing app
```
+------------------------------------------+
|          UI to add team members           |
|  +-------------------------------------+ |
|  |                 Planner             | |
+  +-------------------------------------+ |
+------------------------------------------+

```

# TODO

## Admin
- [x] Create a repo with a terrible code name
- [ ] Write a nice README
- [ ] Add license
- [ ] Set up hosting/deployment (GH Pages the easiest option IMHO) 

## Milestone 1: make a public-facing version of the DS Connect prototype
- [x] Bootstrap a react app + build system (CRA the easiest option IMHO)
- [x] Create a new Mapbox token
- [x] Extract the existing DS Connect UI + logic into a standalone app
- [x] Add to the most simple way possible to add teams. No database, no API (maybe just local storage). Could be: 
    - File input with CSV file or GeoJSON already including coordinates
    - Piece of UI to allow creating/placing team members on a map
- [x] Replace the DS Connect UI with the new imported package 
- [x] I think it would be cool to start the product with a fun preset team, ie, "where should all the Barça players meet to be efficient"
- [ ] About page (could reuse the README contents)

Proposal Planner API for this most minimal MVP:
`
 <Planner team={team data table} />
 `

## Milestone 2: improvements on the prototype
- [ ] Add drag n’drop to the public-facing app
- [ ] Add connectors to the public-facing app
    - Airtable?
    - Google Sheets?
- [ ] Replace MapboxGL with MapLibre and tiles with a simple GeoJSON
- [ ] Separate the core logic from the UI, maybe move to another repo?
- [ ] Allow using different core logics 
    - This would allow using the coarse version currently used, or an async version using a routing API
```
import { Map, ResultsTable, quickAlgo } from @devseed/ghg-planner
...
<Planner team={} algorithm={quickAlgo} />
```
- [ ] Allow customization of internal components (either children via react context or render props)
```
 <Planner team={} algorithm={quickAlgo} />
    <Map /> 
   <ResultsTable />
```

## Milestone 3: more sophisticated routing and CO2eq estimation algorithms
- [ ] Continue benchmarking commercial APIs
- [ ] Work on a way to get real flights in order to call the Google API for CO2 estimates
    - Use a full fledged routing API
    - Or find a static dataset of flights and write a basic routing algorithm on top
- [ ] Add layovers to the logic
- [ ] Investigate into multimodal calculations (trains, maybe buses)
